name: Deploy Frontend via SFTP to Hostinger

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'

jobs:
  deploy:
    name: 🎉 SFTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🚀 Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 88.223.84.94
        port: 65002
        username: u746393752
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: ./public/
        remote_path: /home/u746393752/domains/inprometal.com/public_html/ops/
        sftp_only: true
